language: java
jdk:
  - oraclejdk7
  - oraclejdk8
before_install:
  - pip install --user codecov
script: 
  - ./gradlew build
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)