sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
addons:
  apt:
    packages:
      - lynx
before_install:
  - pip install --user codecov
  - docker --version
  - sudo apt-get update
  - sudo apt-get install -y docker-engine
  - docker --version
  - docker pull redragons/sodra:latest
  - docker-compose --version
  - sudo curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/docker-compose
  - docker-compose --version
script: 
  - ./gradlew build --debug
  - ./gradlew codeCoverageReport --debug
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - if [ -f /home/travis/build/redragons/sodra/sodra-backend/build/reports/tests/test/index.html ]; then lynx -dump /home/travis/build/redragons/sodra/sodra-backend/build/reports/tests/test/index.html; fi